README
stockmarkteam/mind-recommenders-pytorch pull request #1
Opened 2021-12-12 18:18 UTC by kanada0727

2021-12-13 09:45 UTC, acevahir approved these changes

2021-12-13 09:48 UTC, acevahir requested changes
readme typo

2022-03-05 09:15 UTC, kanada0727 commented
@acevahir こちら内容問題なさそうでしたらmainブランチにマージしていただけると助かりますー！

2022-03-05 09:27 UTC, acevahir commented
@kanada0727 私にはWrite権限がないのでマージできませんので月曜日管理者に相談します。

2022-03-07 03:23 UTC, merged